spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/agenda_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.MySQLDialect}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Limitar conexiones del pool Hikari para no pasar el límite de Clever Cloud
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.max-lifetime=300000
spring.datasource.hikari.connection-timeout=20000

spring.application.name=prueba